### ISSUE TITLE
Host Not Permitted Issue in Codespaces and Problems with `bin/dev` and `bin/server` Commands

### ISSUE THREAD

**Issue by bchandhu** [appdev-projects/sinatra-dice-roll#3]
Hi @bpurinton , I am encountering issues when running a Sinatra app in GitHub Codespaces and locally in VS Code. 

### Host Not Permitted in Codespaces and `set :server, 'puma'` Requirement
- When running the app with `ruby app.rb` in GitHub Codespaces, I get a "host not permitted" error. 
- However, the it works without issues when running locally in VS Code with `ruby app.rb`, only  if I explicitly specify `set :server, 'puma'` in the Ruby file. Without this line, it doesn't work.
- Neither `bin/dev` nor `bin/server` commands are working, even though the `puma` server is already set up and defined in the Ruby file.

Thank you!

<img width="610" alt="Screenshot 2024-12-10 at 6 16 11 PM" src="https://github.com/user-attachments/assets/b79e2152-8ca3-4110-b8ab-0220fcd5ccbb">

**Comment by bpurinton** [comment]
I also just tested with:

https://github.com/appdev-projects/sinatra-rps

and

https://github.com/appdev-projects/sinatra-template

But had no issues in a codespace with those.

So it seems like the only issue happens with this blank Sinatra app (https://github.com/appdev-projects/sinatra-dice-roll) and with the instructions given in this lesson in the initial set up: https://learn.firstdraft.com/lessons/103-our-first-sinatra-app

**Comment by bpurinton** [comment]
@bchandhu I got to the bottom of it and fixed the issue by adding `Gemfile.lock` to this project. Now the steps in the lesson https://learn.firstdraft.com/lessons/103-our-first-sinatra-app seem to work and I don't see the error.

I'm not sure about the issues with local setup, but you can try to re-clone this repo and see if it now works locally as well.

However, for this project, it is expected that students are working in a codespace, where it should now work ok.

**Comment by bchandhu** [comment]
Hi @bpurinton, Thank you so much for fixing this! Adding the Gemfile.lock resolved the issue. I re-cloned the repository, and it works perfectly now. I really appreciate your help!

**Comment by bpurinton** [comment]
Update: I've figured out the root cause and am going to remove the `Gemfile.lock` from this project, in favor of the update I made to the lesson: https://learn.firstdraft.com/lessons/103-our-first-sinatra-app#create-a-gemfile

Namely, by adding specific gem versions in the original Gemfile, we can avoid pre-supplying a Gemfile.lock, which is confusing for pedagogical purposes. (We want to start completely blank and show how adding a Gemfile and bundle installing _creates_ the lock file).

The updated first step for this project is to create the Gemfile like so:

```rb
# /Gemfile
source "https://rubygems.org"

gem "puma", "~> 5.6.7"
gem "rackup", "~> 1.0.1"
gem "sinatra", "~> 3.0.6"
```
